export const company = [
    {
        id:1,
        image:'/images/sternweber.jpg'
    },
    {
        id:2,
        image:'/images/myray.jpg'
    },
    {
        id:3,
        image:'/images/cattani.jpg'
    },
    {
        id:4,
        image:'/images/nsk.jpg'
    },
    {
        id:5,
        image:'/images/nouvag.png'
    },
    {
        id:6,
        image:'/images/technogaz.jpg'
    },
    {
        id:7,
        image:'/images/tkd.jpg'
    },
    {
        id:8,
        image:'/images/faro.jpg'
    },
    {
        id:9,
        image:'/images/bodeku.jpg'
    },
    {
        id:10,
        image:'/images/zilfor.jpg'
    },
    {
        id:11,
        image:'/images/sternweber.jpg'
    },
    {
        id:12,
        image:'/images/myray.jpg'
    },
    {
        id:13,
        image:'/images/cattani.jpg'
    },
    {
        id:14,
        image:'/images/nsk.jpg'
    },
    {
        id:15,
        image:'/images/nouvag.png'
    },
    {
        id:16,
        image:'/images/technogaz.jpg'
    },
    {
        id:17,
        image:'/images/tkd.jpg'
    },
    {
        id:18,
        image:'/images/faro.jpg'
    },
    {
        id:19,
        image:'/images/bodeku.jpg'
    },
    {
        id:20,
        image:'/images/zilfor.jpg'
    },
    {
        id:21,
        image:'/images/sternweber.jpg'
    },
    {
        id:22,
        image:'/images/myray.jpg'
    },
    {
        id:23,
        image:'/images/cattani.jpg'
    },
    {
        id:24,
        image:'/images/nsk.jpg'
    },
    {
        id:25,
        image:'/images/nouvag.png'
    },
    {
        id:26,
        image:'/images/technogaz.jpg'
    },
    {
        id:27,
        image:'/images/tkd.jpg'
    },
    {
        id:28,
        image:'/images/faro.jpg'
    },
    {
        id:29,
        image:'/images/bodeku.jpg'
    },
    {
        id:30,
        image:'/images/zilfor.jpg'
    },
    {
        id:31,
        image:'/images/sternweber.jpg'
    },
    {
        id:32,
        image:'/images/myray.jpg'
    },
    {
        id:33,
        image:'/images/cattani.jpg'
    },
    {
        id:34,
        image:'/images/nsk.jpg'
    },
    {
        id:35,
        image:'/images/nouvag.png'
    },
    {
        id:36,
        image:'/images/technogaz.jpg'
    },
    {
        id:37,
        image:'/images/tkd.jpg'
    },
    {
        id:38,
        image:'/images/faro.jpg'
    },
    {
        id:39,
        image:'/images/bodeku.jpg'
    },
    {
        id:40,
        image:'/images/zilfor.jpg'
    },
    
];